insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (1, 'Clarinda', 'aVf2yvZ@', 'Chrissie', '230-644-4753', 'Professor', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (2, 'Culion Island', 'Ironworker', 'Fannie', '372-654-5644', 'Analog Circuit Design manager', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (3, 'Houma', 'Ironworker', 'Zaria', '921-901-6334', 'Media Manager II', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (4, 'Recife', 'Tile Setter', 'Alisun', '868-948-4104', 'Budget/Accounting Analyst I', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (5, 'Sege', 'Plasterers', 'Pennie', '940-551-8764', 'Financial Analyst', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (6, 'Nacala', 'Millwright', 'Gertruda', '517-268-7651', 'VP Marketing', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (7, 'Tobermorey', 'Safety Officer', 'Harli', '136-238-7702', 'VP Sales', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (8, 'Mende/Brénoux', 'HVAC', 'Rosalia', '524-152-5660', 'Help Desk Technician', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (9, 'Bouarfa', 'Refridgeration', 'Eugenie', '913-369-7000', 'Executive Secretary', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (10, 'Bucharest', 'Sheet Metal Worker', 'Nina', '688-278-3563', 'Payment Adjustment Coordinator', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (11, 'Kepi-Papua Island', 'Tile Setter', 'Ashley', '595-588-1044', 'Geologist III', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (12, 'Cairo', 'Waterproofer', 'Antonia', '202-338-4567', 'Tax Accountant', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (13, 'Butare', 'Plasterers', 'Martita', '978-322-8638', 'Engineer I', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (14, 'Buenaventura', 'Welder', 'Min', '472-388-3046', 'Human Resources Assistant II', now(), now());
insert into user (id, username, password, name, phone, job , reg_date, mod_date) values (15, 'opera', 'Equipment Operator', 'Antonie', '658-863-0908', 'Physical Therapy Assistant', now(), now());